### ISSUE TITLE
Assign image and description to field layout globally, not to specific field layout instances within matrix fields

### ISSUE THREAD

**Issue by piotrpog** [mediakreativ/craft-blocksmith#2]
I sometimes reuse field layouts blocks within multiple matrix fields. In such situation,i would need to enter field layout block description (and image) multiple times. This would be hard to maintain.

**Comment by schindlerchristian** [comment]
Hi @piotrpog,  

thank you for bringing this up and for taking the time to share your thoughts! Your point about reusing field layout blocks across multiple matrix fields and the potential maintenance challenges is spot on.  

### Current Behavior:
At the moment, the **Blocksmith Configure Blocks overview** displays blocks grouped by their assigned Matrix fields. While this layout might suggest that you can configure a block's description or preview image individually for each Matrix field, that's actually not the case. Currently, any updates to a block’s settings (e.g., description, preview image, etc.) apply globally across all Matrix fields where the block is used.  

### Planned Adjustment:
To avoid confusion, I plan to redesign the overview page so that each block is listed only once, regardless of how many Matrix fields it’s assigned to. Additionally, I’m considering showing badges or labels within each block card to indicate which Matrix fields it belongs to. This will make it clear that the settings are currently global while maintaining an intuitive overview.  

### Inspired by Your Suggestion:
Your suggestion also inspired me to think further:  
There are valid use cases where users might want to have **individual settings per Matrix field** for the same block. For example:  
- Different descriptions based on the context of the Matrix field.  
- Different preview images if a block is styled differently in different areas of the site.  

This is such a great idea that I’ve added it to the **Blocksmith Roadmap** as a future feature. While this level of customization is currently not supported, I think it would be a valuable addition for many users.  

### Next Steps:
1. I’ll first update the overview to avoid any confusion about global vs. field-specific settings.  
2. In the future, I’ll explore how to introduce per-Matrix-field customizations for blocks in a way that keeps the interface intuitive and flexible.  

Thanks again for highlighting this! Your input is incredibly helpful in making Blocksmith better for everyone. If you have further thoughts or specific use cases you’d like to see addressed, feel free to share them—I’d love to hear more.  

Best regards,  

Christian
